# Generated by Django 4.0.4 on 2022-05-22 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_rename_accrued_interest_unlistedbondholding_interest_rate_and_more'),
        ('loader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFHoldingFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loader.file')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.bankaccount')),
            ],
            bases=('loader.file',),
        ),
    ]
