# Generated by Django 4.0.4 on 2022-05-22 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_rename_accrued_interest_unlistedbondholding_interest_rate_and_more'),
        ('loader', '0002_mfholdingfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfholdingfile',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.demataccount'),
        ),
    ]
