# Generated by Django 4.0.4 on 2022-05-12 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bullion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Platinum', 'Platinum'), ('Palladium', 'Palladium'), ('Other', 'Other')], max_length=100)),
                ('default_unit', models.CharField(choices=[('Kg', 'Kg'), ('Gram', 'Gram'), ('Pound', 'Pound'), ('Ounce', 'Ounce'), ('Other', 'Other')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DebtSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('face_value', models.FloatField()),
                ('maturity_date', models.DateField()),
                ('maturity_amount', models.FloatField()),
                ('interest_rate', models.FloatField(null=True)),
                ('ip_frequency', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half-Yearly', 'Half-Yearly'), ('Yearly', 'Yearly'), ('Maturity', 'Maturity')], max_length=50)),
                ('ip_amount', models.FloatField(default=0)),
                ('ip_date', models.DateField(null=True)),
                ('is_interest_rate_floating', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MutualFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100, null=True)),
                ('plan', models.CharField(max_length=100, null=True)),
                ('expense_ratio', models.FloatField(null=True)),
                ('aum', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterparty', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('interest_rate', models.FloatField(null=True)),
                ('amount', models.FloatField()),
                ('transaction_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Recievables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterparty', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('transaction_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=100)),
                ('isin_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FD',
            fields=[
                ('debtsecurity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='securities.debtsecurity')),
                ('issuer', models.CharField(choices=[('SBI', 'SBI'), ('ICICI', 'ICICI'), ('HDFC', 'HDFC'), ('KOTAK', 'KOTAK'), ('AXIS', 'AXIS'), ('PNB', 'PNB'), ('YES', 'YES'), ('RBL', 'RBL'), ('INDUSIND', 'INDUSIND')], max_length=100)),
            ],
            bases=('securities.debtsecurity',),
        ),
        migrations.CreateModel(
            name='ListedNCD',
            fields=[
                ('debtsecurity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='securities.debtsecurity')),
                ('symbol1', models.CharField(max_length=50)),
                ('isin_code', models.CharField(max_length=50)),
                ('dirty_price', models.FloatField()),
                ('clean_price', models.FloatField()),
                ('secured', models.BooleanField()),
                ('issuer', models.CharField(max_length=100)),
            ],
            bases=('securities.debtsecurity',),
        ),
        migrations.CreateModel(
            name='OtherUnlistedBonds',
            fields=[
                ('debtsecurity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='securities.debtsecurity')),
                ('issuer', models.CharField(max_length=100)),
            ],
            bases=('securities.debtsecurity',),
        ),
        migrations.CreateModel(
            name='SavingsBond',
            fields=[
                ('debtsecurity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='securities.debtsecurity')),
                ('issuer', models.CharField(default='GOI', max_length=100)),
            ],
            bases=('securities.debtsecurity',),
        ),
    ]
