# Generated by Django 4.0.4 on 2022-05-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfund',
            name='symbol',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
