# Generated by Django 4.0.4 on 2022-05-15 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0003_alter_listedncd_clean_price_alter_listedncd_issuer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FD',
        ),
    ]
