# Generated by Django 4.0.4 on 2022-05-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0004_delete_fd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bullion',
            name='name',
        ),
        migrations.AddField(
            model_name='bullion',
            name='symbol',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bullion',
            name='default_unit',
            field=models.CharField(max_length=50),
        ),
    ]
