# Generated by Django 4.0.4 on 2022-05-13 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0001_initial'),
        ('portfolio', '0003_stockbuytrade_trade_id_stockselltrade_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demataccount',
            name='balance',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='MutualFundSellTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('buy_price', models.FloatField()),
                ('sell_price', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('trade_date', models.DateField()),
                ('profit', models.FloatField(null=True)),
                ('trade_id', models.UUIDField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.demataccount')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.mutualfund')),
            ],
        ),
        migrations.CreateModel(
            name='MutualFundHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('buy_price', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.demataccount')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.mutualfund')),
            ],
        ),
        migrations.CreateModel(
            name='MutualFundBuyTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('trade_date', models.DateField()),
                ('trade_id', models.UUIDField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.demataccount')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.mutualfund')),
            ],
        ),
        migrations.CreateModel(
            name='BullionSellTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('buy_price', models.FloatField()),
                ('sell_price', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('trade_date', models.DateField()),
                ('profit', models.FloatField(null=True)),
                ('trade_id', models.UUIDField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.generalaccount')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.bullion')),
            ],
        ),
        migrations.CreateModel(
            name='BullionHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('buy_price', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.generalaccount')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.bullion')),
            ],
        ),
        migrations.CreateModel(
            name='BullionBuyTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('trade_date', models.DateField()),
                ('trade_id', models.UUIDField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.generalaccount')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.bullion')),
            ],
        ),
    ]
