# Generated by Django 4.0.4 on 2022-05-15 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0004_delete_fd'),
        ('portfolio', '0004_alter_demataccount_balance_mutualfundselltrade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlistedBondHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('bond_yield', models.FloatField(null=True)),
                ('buy_price', models.FloatField(null=True)),
                ('clean_price', models.FloatField(null=True)),
                ('accrued_interest', models.FloatField(null=True)),
                ('total_amount', models.FloatField(null=True)),
                ('buy_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.demataccount')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.otherunlistedbonds')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsBondHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('bond_yield', models.FloatField(null=True)),
                ('buy_price', models.FloatField(null=True)),
                ('clean_price', models.FloatField(null=True)),
                ('accrued_interest', models.FloatField(null=True)),
                ('total_amount', models.FloatField(null=True)),
                ('buy_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.generalaccount')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.savingsbond')),
            ],
        ),
        migrations.CreateModel(
            name='ListedNCDSellTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('buy_price', models.FloatField()),
                ('sell_price', models.FloatField()),
                ('total_amount', models.FloatField(null=True)),
                ('profit', models.FloatField(null=True)),
                ('buy_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.generalaccount')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.savingsbond')),
            ],
        ),
        migrations.CreateModel(
            name='ListedNCDHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('bond_yield', models.FloatField(null=True)),
                ('buy_price', models.FloatField(null=True)),
                ('clean_price', models.FloatField(null=True)),
                ('accrued_interest', models.FloatField(null=True)),
                ('total_amount', models.FloatField(null=True)),
                ('buy_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.demataccount')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.listedncd')),
            ],
        ),
        migrations.CreateModel(
            name='ListedNCDBuyTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('total_amount', models.FloatField(null=True)),
                ('buy_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.generalaccount')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.savingsbond')),
            ],
        ),
        migrations.CreateModel(
            name='FixedDepositHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('ip_frequency', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half-Yearly', 'Half-Yearly'), ('Yearly', 'Yearly'), ('Maturity', 'Maturity')], max_length=50)),
                ('start_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('maturity_amount', models.FloatField()),
                ('is_interest_rate_floating', models.BooleanField(default=False)),
                ('isin_code', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.bankaccount')),
            ],
        ),
    ]
