# Generated by Django 4.0.4 on 2022-05-16 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_unlistedbondholding_savingsbondholding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listedncdbuytrade',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.demataccount'),
        ),
        migrations.AlterField(
            model_name='listedncdselltrade',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.demataccount'),
        ),
    ]
