# Generated by Django 4.0.4 on 2022-05-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_listedncdbuytrade_security_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedncdbuytrade',
            name='trade_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='listedncdselltrade',
            name='trade_date',
            field=models.DateField(null=True),
        ),
    ]
