# Generated by Django 4.0.4 on 2022-05-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_listedncdbuytrade_trade_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedncdbuytrade',
            name='trade_id',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='listedncdselltrade',
            name='trade_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
