# Generated by Django 4.0.4 on 2022-05-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_listedncdbuytrade_trade_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listedncdholding',
            name='price',
        ),
    ]
