# Generated by Django 4.0.4 on 2022-05-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_listedncdholding_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixeddepositholding',
            name='ip_frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('HalfYearly', 'HalfYearly'), ('Yearly', 'Yearly'), ('Maturity', 'Maturity')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fixeddepositholding',
            name='isin_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
