# Generated by Django 4.0.4 on 2022-05-16 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_fixeddepositholding_ip_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unlistedbondholding',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.generalaccount'),
        ),
    ]
