# Generated by Django 4.0.4 on 2022-05-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_unlistedbondholding_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unlistedbondholding',
            old_name='accrued_interest',
            new_name='interest_rate',
        ),
        migrations.RenameField(
            model_name='unlistedbondholding',
            old_name='clean_price',
            new_name='maturity_amount',
        ),
        migrations.RemoveField(
            model_name='unlistedbondholding',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='unlistedbondholding',
            name='security',
        ),
        migrations.RemoveField(
            model_name='unlistedbondholding',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='unlistedbondholding',
            name='ip_frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('HalfYearly', 'HalfYearly'), ('Yearly', 'Yearly'), ('Maturity', 'Maturity')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unlistedbondholding',
            name='maturity_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='unlistedbondholding',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unlistedbondholding',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
